In [9]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a[1,2])
print(a[1:,1:])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
6
[[5 6]
 [8 9]]


In [2]:
b=np.array([1,2,3,4,5,6,7,8,9])
c=b.reshape(3,3)
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
d=np.arange(9).reshape(3,3)
print(d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [5]:
e=np.zeros((3,3),dtype='i')
print(e)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [6]:
e=np.ones((3,3),dtype='i')
print(e)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [14]:
#program to perform matrixmultiplication
import numpy as np
a=np.array([[1,2],[3,4]])
print("first matrix:\n",a)

b=np.array([[5,1],[2,4]])
print("second matrix:\n",b)

c=np.dot(a,b)

print("Matrix multiplication:\n",c)

print("Transpose :\n",c.transpose())

first matrix:
 [[1 2]
 [3 4]]
second matrix:
 [[5 1]
 [2 4]]
Matrix multiplication:
 [[ 9  9]
 [23 19]]
Transpose :
 [[ 9 23]
 [ 9 19]]


In [16]:
#program to perform svd 
import numpy as np
from scipy.linalg import svd
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
v,s,t=svd(a) #to find svd
print("\n v=",v)
print("\n s=",s)
print("\n t=",t)

e=(v @ np.diag(s) @t) #to get old matrix
print("\n",e)


 v= [[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]

 s= [1.68481034e+01 1.06836951e+00 4.41842475e-16]

 t= [[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]

 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
